### ISSUE TITLE
Finalize Garden v0 UI/UX design

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#104]
_As a Developers, we want to agree on the wireframes for the Garden UI before we implement them. Additionally, we need to make any final design decisions for v0_

# Assumptions
- We as a team have already decided on whether or not to include features that are in the wireframe
- Any design decisions not already made can be discussed in this meeting, or tabled for a larger group discussion

# Acceptance criteria
1. Constructive feedback is given on the UI wireframes such that we as developers can move forward with a v0 implementation
2. Any design decisions that still need to be made are recorded and a plan is made to address them with the larger team

# Tasks 

- [ ] Coordinate meeting time -- Wednesday April 12th at 12pm CT
- [ ] Prepare agenda with questions to address (might include design decision questions)
- [ ] Record state of decisions and feedback in meeting
- [ ] Follow up on any remaining design decisions

**Comment by ascourtas** [comment]
Final decisions were recorded in the [Garden UI/UX Feedback Meeting Agenda](https://docs.google.com/document/d/1b5CN2JMEa_2Qx4-YAnbXrrVJYLWphiB_aB4woioMM0o/edit#) document.

Any other context is available in the [Garden UI/UX Questions](https://docs.google.com/document/d/1IYCd5QoS31NMtPx0-nrbHfbDijr0sn2WeGBDZFftX0k/edit) document
