### ISSUE TITLE
DLHub -> Pipeline/Garden migration script (Isaac internship)

### ISSUE THREAD

**Issue by OwenPriceSkelly** [Garden-AI/garden#112]
_As a proud owner of a working dlhub servable, I'd like to migrate to an equivalent working garden/pipeline._

(This story is just for keeping track of progress and scaffolding tasks for Isaac's ongoing work on a script to migrate users from dlhub to garden.)

# Assumptions:
1. I have working dlhub code/files for my published model and associated `dlhub.json` metadata and relevant files (can be fetched from doi or unique title, provided by user) 
2. Input to script:
    - username, servable name, globus authenticated user, ...  
3. output of script:
    - (tentative, garden-side interface/ux might change) a `pipeline.py` file with a scaffolded pipeline, plus as much information/metadata automatically populated as possible. The relevant models would have been registered with the garden backend s.t. they can be referenced by uri like "models:/my-model-name/latest" in the pipeline code. 
    - calling the pipeline defined here should be equivalent to calling `dlhub.Client.run(...)` 

## requirements for pipeline/garden-side 
- author/title/doi metadata (from dlhub.json) 
- pre-trained model file(s) to register (model.pkl etc) 

# tasks:
- [x] fetch dlhub metadata step
~- [ ] new endpoint for dlhub_service to download all servable files/data~
  ~- [ ] probably going to look a lot like `api_edit_servable`~ 
- [ ] new endpoint for dlhub_service to re-register model with Garden
  - [ ] WIP: https://github.com/DLHub-Argonne/dlhub_service/pull/37
    - [x] use garden sdk or cli to register pre-trained model file(s)
      - gives us a model uri like "models:/my-model-name/latest"  
- [ ] populate pipeline step(s) (which references e.g. `Model("models:/my-model-name/latest")` somewhere)
- [ ] register the new pipeline if possible, or instruct user on how to finish registration 

# Acceptance Criteria
Given the unique title of a servable like "test/candle_p1b1" (ex from dlhub site), 
when invoking this standalone CLI utility, 
then I have a pre-populated `pipeline.py` file which is ready to register with garden (to the extent possible) 

edit: current approach is to try and register the model and pipeline directly, without templating a partial `pipeline.py` file (like described above)

**Comment by OwenPriceSkelly** [comment]
Current status of this project: 
- Isaac's script when tested against his [dlhub_service PR](https://github.com/DLHub-Argonne/dlhub_service/pull/39) is able to at least reliably extract a `model.pkl` artifact from inside the servable container 
- Blocker: the script, running locally, can't re-register the `model.pkl` with garden unless it's able to deserialize `model.pkl` locally, i.e. local package versions are an exact match.
- A workaround is definitely possible, but way out of scope for an internship and probably out of scope for v0/v1, so we're putting a pin in this in favor of more tractable garden stories.
