### ISSUE TITLE
Make some early website metadata decisions

### ISSUE THREAD

**Issue by ascourtas** [Garden-AI/garden#194]
_More metadata is needed in this iteration to have a meaningful web UI. Add a little bit more metadata (just a bit!) to get us moving_

# Assumptions:
1.
2.

# Acceptance Criteria
Given..., when..., then...

# Tasks 
- [x] Chase looks into what metadata might be needed
- [ ] Mentors review and make final decisions on metadata for this current iteration
- [ ] Chase adds that metadatga

**Comment by kjschmidt913** [comment]
From Chase: 

Metadata (priority of lists from top to bottom) :

- Datasets
     - DOI
     - Title
     - Where its hosted
     - File Size
     - Data type
- Repository
     - Link
     - Repository Name
     - Contributors
- Papers
     - Title
     - Authors
     - DOI
     - Citation

**Comment by WillEngler** [comment]
Gonna close in favor of #210 (Chase is good to implement)
