### ISSUE TITLE
Hello, Garden

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#2]
_As a Garden Publisher I want to access the API via the Garden SDK so I can share my models_

# Assumptions:
1. There will be a `GardenClient` class in the `garden` package
2. The constructor doesn't take any arguments
3. There is a CI job on branch pushes and on PRs that will:
  a. Run Flake8
  b. Run [mypy](https://mypy.readthedocs.io/en/stable/)
  c. Check requirements.txt against known vulnerabilities using [safety](https://pypi.org/project/safety/)
  d. Runs pytest with code coverage
  e. Pushes code coverage report to [codecov.io](https://about.codecov.io)

# Acceptance Criteria
Given I have garden-ai package installed, when I execute the following python code:
```python
from garden import GardenClient
client = GardenClient()
print(client)
```
Then I don't have any errors.

Given I push a commit to a branch that has flake8 errors, when the CI job runs, Then it reports an error and fails

# Tasks

- [x] Add basic `GardenClient` in `garden` package 
- [x] Set up CI to publish `garden` package to PyPI on GitHub release -- https://github.com/Garden-AI/garden/pull/1
- [x] Set up CI to run tests and flake8 on push (and create dummy tests) -- https://github.com/Garden-AI/garden/pull/6 (also looks like this was addressed in some un-PR'd code pushed to main)
- [ ] Add mypy usage for type checking  
- [ ] Add safety usage for checking requirements.txt
- [ ] Add  code-cov usage and report pushing

**Comment by blaiszik** [comment]
Here's to many more amazing stories and accomplishments from Garden in the future! :seedling:

**Comment by ascourtas** [comment]
@BenGalewsky so this is linked to the PRs #6 and #1, right? In the past I've operated under the 1 issue 1 branch 1 PR rule, which feels a little easier to track. What do you and @blaiszik think, ie what have you found to be best practice? 
Similarly, this story feels like multiple GitHub Issues to me, but from what I've learned it seems that 1 issue == 1 user story is best practice -- are either of ya'll opposed to using that as a guideline for the future?

**Comment by BenGalewsky** [comment]
"Assumptions" are some clues on how to implement this story. Without them, the only judgement would be could you meet the success criteria. The Assumptions are some specifications of the "How".

There is no requirement that the issue is a single PR. In fact, most interesting stories might cross several repos. For example a Story could require a change to the SDK and to the server.

**Comment by ascourtas** [comment]
I think it's confusing that Assumptions could include both items that are already true, and items that are not and need to be addressed in the current story/issue -- I feel like that will lead to a lot of unnecessary cross-checking of other stories/issues to see what has been done and what hasn't when picking up an issue/story, which doesn't scale well. However, I do understand that writing the Assumptions from a purely user-perspective, without thinking about what has already been implemented, is useful. 

Maybe we can add a Tasks section (that the person who picks up the story can then edit later) that outlines some of the basic tasks in mind at the time of story/issue creation? I think that could potentially help disambiguate

**Comment by ascourtas** [comment]
@BenGalewsky I asked @kjschmidt913 and @blaiszik for their thoughts, and we're thinking that a higher-level story (which as you mentioned, could span multiple repos) could have sub-issues that are linked, and that would help disambiguate while still being true to the user story and not getting lost in technical details. What are your thoughts?

**Comment by ascourtas** [comment]
To wrap the above thread: we discussed in Slack and in meetings keeping the issues as higher-level Stories, with detailed discussion split between the issue and the PR itself (we will evaluate how this goes). 

The key is breaking out those stories into tasks that are linked to any associated PRs, so we don't lose track of what is done and what is not.

**Comment by ascourtas** [comment]
I believe https://github.com/Garden-AI/garden/pull/12 just resolved the remaining tasks for this issue? Closing unless someone suggests otherwise
