### ISSUE TITLE
Authenticate With Garden Client

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#3]
_As a Garden Publisher I want to authenticate with Globus so I can have permission to publish my model_

# Assumptions:
1. There will be a Garden globus app
2. The constructor will obtain tokens via GlobusAuth3. 
3. Tokens will be persisted in the user's `.garden` directory 
4. Story is burdened with setting up readthedocs 

# Acceptance Criteria
1. Given I have garden installed in my python environment, and it is the first time I've used the GardenClient when I execute python code to instantiate a GardenClient, Then I will be presented with a link to authenticate and an opportunity to paste a token and it will be accepted.
2. Given I have garden installed in my python environment and I've successfully authenticated the GlobusClient, when I execute python code to instantiate a GardenClient then it will not ask for me to follow the link and paste a token

# Tasks
- [x] Create Garden Application in [https://auth.globus.org/v2/web/developers](https://auth.globus.org/v2/web/developers)
- [x] Update project to use poetry and include mypy and safety in CI (PR #12 )
- [x] Code up auth workflow in client constructor (PR #13)
- [x] Code up unit testing strategy for auth as well as testing out authenticated methods (PR #13)
- [x] Create readthedocs flow with Sphinx api documentation

**Comment by BenGalewsky** [comment]
@blaiszik - I assume that you should own the Garden application on globus auth? Also, do we have a secure way to share the secrets? My go-to would be lastpass

**Comment by BenGalewsky** [comment]
@ericblau do you have a terrific example of doing Globus Auth from a python client? I want our implementation to be a textbook example.

I looked at the [funcX client](https://github.com/funcx-faas/funcX/blob/fe54444868e7393d60be03db4c1b426df32a2d51/funcx_sdk/funcx/sdk/client.py#L151) and it seems incredibly complicated - I don't think we need anything that sophisticated!

**Comment by BenGalewsky** [comment]
> Do we need to share the credentials, or could we just have them in GH Secrets?

You typically need to know them for development. On another project we kept passing them around on slack which is not particularly great.

**Comment by blaiszik** [comment]
They are now available through CLIENT_ID and CLIENT_SECRET in GitHub secrets

**Comment by ericblau** [comment]
OK, just so I'm clear:  this is a client that is installed on the users's machine?  That implies that it will need to be a NativeAppAuthClient as otherwise the user would have access to the CLIENT_SECRET.  This would require a browser to be spawned, but we can have it automatically return to the app, without having to paste a code.

**Comment by ericblau** [comment]
So, https://github.com/globus/native-app-examples has a few native app examples--I'd suggest looking in particular at https://github.com/globus/native-app-examples/blob/main/example_local_server.py as it gives an example that does not require a cut and paste of codes.  

I'd also recommend looking at https://globus-sdk-python.readthedocs.io/en/stable/examples/group_listing.html#group-listing-with-token-storage which is a good example of using the Globus SDK v3 TokenStorage and refresh tokens.

**Comment by BenGalewsky** [comment]
This is complete.
Take a look at the docs: https://garden-ai.readthedocs.io/en/latest/

Unit test code coverage report works too: https://app.codecov.io/gh/Garden-AI/garden

Published this to pypi: https://pypi.org/project/garden-ai/

[Example code](https://github.com/Garden-AI/garden/blob/main/examples/basic_example.py) works and requests token. Second time around it skips this

**Comment by Aadit-Ambadkar** [comment]
I just tested this, and it looks like authentication works and doesn't ask for it a second time like @BenGalewsky said above.
