### ISSUE TITLE
Garden Create Command

### ISSUE THREAD

**Issue by BenGalewsky** [Garden-AI/garden#46]
_As a model contributor I want to be able to create a new garden so others can find my pipelines_

# Description
There is a command line interface to garden. It is installed with `pip install garden-ai` alongside the garden SDK.  It has a command line argument parser.

For this story we will add the `create` command to the CLI. This creates a new garden.
It takes command line arguments to pick up all of the mandatory garden properties. If command line args are missing it will prompt for values _wizard style_.

The result is a minimally valid `garden.json` with a UUID that was generated in the cli. The command will create a basic garden directory structure.

NOTE: the behavior implemented by the linked PR is slightly different from what's described here -- it scaffolds a directory for the user _if one is specified_, but if left blank it does not perform any scaffolding. Also a slight departure is the `garden.json`, which is written to `~/.garden/db/gardens/{garden uuid}.json` instead; if `--verbose` is set the contents of the json will be pretty-printed when created.

The basic garden directory structure will be:
```
{pwd}/
    models/
      .gitignore
    
    pipelines/
      {pipeline_name}.py  # not this story
    
    README.md # populated with provided description? 
    
    garden.json # generated from Garden object if user input is all valid

```
NOTE: best practice to do a `git init` for user or to ask them to `git init` before `garden create`? 

## separable tasks 
- [x] CLI/wizardry prompting part 
- [x] directory scaffolding part 
    - should be implemented as a function `f(directory : str) -> str` 
    - sets up the directory if the proposed name is valid (returning the input unmodified)
    - `raise typer.Exit(code=1)` otherwise
- [x] unit tests

### Tasks

- [x] garden init should check that the current directory is empty 
- [x] keep directory-making behavior analogous to `git init` 
- [ ] README with light documentation on the purpose of the CLI
- [x] PyPI packaging and deployment 
- [x] Decide on skeleton file structure
- [x] Create gh action
- [x] Wizard prompting
- [x] Tests for basic create action
- [x] typer/pydantic integration

- [x] `garden create` makes the skeleton directory (pathlib module has all the helpers we'd need)  
- [x] `garden create` prompts user and instantiates a Garden object and write garden.json 
...

# Assumptions:
1. The command is issued in the root folder of a newly created git repository.
2. The models directory is just a suggestion where users could put code for training models.
3. The models/.gitignore file has entries for common model files. We want to actively discourage users from saving their models in git. They should use the Garden model repository for this.
4. the pipelines directory should be empty 
5. the garden's metadata is stored locally at `~/.garden/db/{garden uuid}.json`, and can be printed to stdout by passing a `--verbose` flag

**Comment by blaiszik** [comment]
Small comment. I suspect we will need a garden-ai SDK, should this be `pip install garden-ai-cli`?

**Comment by blaiszik** [comment]
One tool that may be helpful for building the text wizards and templates.
https://github.com/Textualize/textual

via Owen: Nomination for cli-wizardry: https://typer.tiangolo.com

**Comment by blaiszik** [comment]
Example ChatGPT code 

```script.py
import typer
import json
import datetime

app = typer.Typer()

def create_garden(name: str, date_created: str, description: str):
    garden = {
        "name": name,
        "date_created": date_created,
        "description": description
    }
    with open(f"garden.json", "w") as f:
        json.dump(garden, f)
    typer.echo(f"Garden {name} created successfully.")

@app.command()
def create(
    name: str = typer.Option(None),
    date_created: str = typer.Option(None),
    description: str = typer.Option(None),
):
    """Create a Garden entity."""
    if not name:
        name = typer.prompt("Enter garden name: ")
    if not date_created:
        date_created = typer.prompt("Enter date created (YYYY-MM-DD): ", type=str)
    while True:
        try:
            date_created = datetime.datetime.strptime(date_created, '%Y-%m-%d').strftime('%Y-%m-%d')
            break
        except ValueError:
            date_created = typer.prompt("Invalid date format. Enter date created (YYYY-MM-DD): ", type=str)
    if not description:
        description = typer.prompt("Enter description: ")
    create_garden(name, date_created, description)

@app.command()
def other(test=True):
    """Other command."""
    typer.echo(f"Other command called with test={test}")

if __name__ == "__main__":
    app()
```

**Comment by BenGalewsky** [comment]
> Small comment. I suspect we will need a garden-ai SDK, should this be `pip install garden-ai-cli`?

There should just be one package. Installing the SDK also installs the CLI

**Comment by WillEngler** [comment]
Alternate assumptions (debatable, not gospel):
1. garden create should not create a directory structure
2. It should mint a DOI at creation time. (Because there is no separate step of creating and then publishing for gardens.)

Otherwise, same as what Ben G wrote
